version: '3.3'

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - $DB_PORT:$DB_PORT
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql
  
volumes:
  db:

networks:
  backend: